config/routes.rb
Rails.application.routes.draw do
  resources :payment_users
  resources :payments, except: [:show, :destroy]
  resources :users, except: [:show, :destroy]

  root 'users#login'

  get 'login' => 'users#login', as: :login

  get 'signup' => 'users#new', as: :signup

  get '/history' => 'payments#history', as: :history

  post '/login' => 'users#authenticate'

  post '/paid' => 'payments#paid', as: 'paid'

  delete 'logout/:id' => "users#logout", as: :logout

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  # TS - instead of this table, you should do this more intuitively
  # TS - i.e. a `has_one :recipient, class_name: 'User'` and `has_one :sender, class_name: 'User'`
	has_many :payment_users
	has_many :users, through: :payment_users
	belongs_to :type
	validates_presence_of :sender_id, :recipient_id, :note
	validates :amount, :presence=>true,
						:numericality => true
  validates_format_of :amount, :with => /\A\d+(?:\.\d{0,2})?\z/

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # TS - Since you use current_user in those methdos, add :index, :history to this only:
  before_action :require_login, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    # TS - unnecessary interpolation
    @sender_payments = Payment.where(sender_id: "#{current_user.id}", paid: false).all
    @recipient_payments = Payment.where(recipient_id: "#{current_user.id}", paid: false).all

    @net_total = current_user.owed
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
    # TS - Payment.find assumes you're passing in an id as the sole argument; find_by_id is overly verbose
    # TS - Additionally, I would call set_payment here or in a before_action
    @payment = Payment.find_by_id(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    if payment_params[:sender_id] != payment_params[:recipient_id]
      if @payment.save
        redirect_to payments_path
        flash[:success] = "Payment created successfully!"
      else
        flash.now[:error] = @payment.errors.full_messages
        render :new
      end
    else
      # TS - Instead of clearing your flash errors, just ensure that it's an array with `flash.now[:error] ||= []`
      flash.now[:error] = []
      flash.now[:error] << "Sender and recipient must be different."
      render :new
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    set_payment
      if @payment.update(payment_params)
        redirect_to payments_path
        flash[:success] = "Payment updated successfully!"
      else
        flash.now[:error] = @payment.errors.full_messages
        render :edit
    end
  end

  def paid
    # TS - I would call set_payment here or in a before_action
    payment = Payment.find(params[:id])
    unless payment.paid?
      payment.update_attribute(:paid, true)
      render json: { msg: true, amount: current_user.owed }
    else
      render json: { msg: 'Already paid' }
    end
  end

  def history
    @history = Payment.where("(sender_id = ? OR recipient_id = ?) AND paid = ?", "#{current_user.id}", "#{current_user.id}", true )
    @history = @history.sort.reverse
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:title, :sender_id, :recipient_id, :amount, :type_id, :note)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<% content_for :body_class, "form-style" %>
<!-- TS - We in Ruby 2.0, what's up with using a hash rocket -->
<%= form_for(@payment, :html => { :class=>"payment-form" } ) do |f| %>

  <div class="field form-group">
    <%= f.label :sender_id %>
    <%= f.collection_select :sender_id, User.all, :id, :full_name, { :include_blank=> true }, { :class=>"form-control" } %>
  </div>
  <div class="field form-group">
    <%= f.label :recipient_id %><br>
    <%= f.collection_select :recipient_id, User.all, :id, :full_name, { :include_blank=> true }, { :class=>"form-control" } %>
  </div>
  <div class="field form-group">
    <%= f.label :amount %><br>
    <div class="input-group">
      <span class="input-group-addon">$</span>
      <%= f.text_field :amount, :class=>"form-control", :value=>(number_with_precision(f.object.amount, :precision=>2)) %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :note %><br>
    <%= f.text_area :note, :class=>"form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit (f.object.new_record? ? "Create" : "Update"), :class=>"btn btn-default submit-button" %>
  </div>
<% end %>

app/views/payments/_green_arrow.html.erb
<td class="owe-arrow">
          <svg width="300" height="70" xmlns="http://www.w3.org/2000/svg">
            <g>
              <polyline points=" 50,0 78.383,34.383 50,66.766 " fill="#0f0">
                <animate attributeName="points"
                         from="0,0 28.383,34.383 0,66.766 "
                         to="50,0 78.383,34.383 50,66.766 "
                         dur="1s"
                         repeatCount="forwards"
                         fill="freeze"/>
              </polyline>
              <polyline points="0,0 28.383,34.383 0,66.766" fill="#0f0">
                <animate attributeName="points"
                         from="0,0 28.383,34.383 0,66.766 "
                         to="130,0 158.383,34.383 130,66.766 "
                         dur="1s"
                         repeatCount="forwards"
                         fill="freeze"/>
              </polyline>
              <polyline points="0,0 28.383,34.383 0,66.766" fill="#0f0">
                <animate attributeName="points"
                         from="0,0 28.383,34.383 0,66.766 "
                         to="210,0 238.383,34.383 210,66.766 "
                         dur="1s"
                         repeatCount="forwards"
                         fill="freeze"/>
              </polyline>
            </g>
          </svg></td>

app/views/payments/_red_arrow.html.erb
<td class="owe-arrow">
          <svg width="300" height="70" xmlns="http://www.w3.org/2000/svg">
            <g>
              <polyline points=" 300,0 271.617,34.383 300,66.766 " fill="#f00">
                <animate attributeName="points"
                         from=" 300,0 271.617,34.383 300,66.766 "
                         to="240,0 211.383,34.383 240,66.766 "
                         dur="1s"
                         repeatCount="forwards"
                         fill="freeze"/>
              </polyline>
              <polyline points=" 300,0 271.617,34.383 300,66.766 " fill="#f00">
                <animate attributeName="points"
                         from=" 300,0 271.617,34.383 300,66.766 "
                         to="160,0 131.383,34.383 160,66.766 "
                         dur="1s"
                         repeatCount="forwards"
                         fill="freeze"/>
              </polyline>
              <polyline points=" 300,0 271.617,34.383 300,66.766 " fill="#f00">
                <animate attributeName="points"
                         from=" 300,0 271.617,34.383 300,66.766 "
                         to="80,0 51.383,34.383 80,66.766 "
                         dur="1s"
                         repeatCount="forwards"
                         fill="freeze"/>
              </polyline>
            </g>
          </svg>
        </td>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<div class="cancel-link">
<%= link_to 'Cancel', payments_path %>
</div>

<% flash.each do |type, messages| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in error-message">
      <ul class="errors">
        <% messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/payments/history.html.erb
<% content_for :body_class, "payment-page form-style" %>

<h1>Payment History</h1>
<div class="new-payment-link"><%= link_to 'Back', payments_path, :class=>"btn btn-default" %></div>
<% if @history.present? %>
<table class="payment-table">
  <tbody>
    <% @history.each do |payment| %>
      <tr class="payment-<%= payment.id %>">
      <% if payment.sender_id == current_user.id %>
        <td class="payment-user"><%= User.find_by_id(payment.recipient_id).first_name %></td>   
        <td class="owe-arrow">
          <svg width="100" height="70" xmlns="http://www.w3.org/2000/svg">
            <g>
              <polyline points=" 80,0 51.383,34.383 80,66.766 " fill="#f00"></polyline>
            </g>
          </svg>
        </td>
        <% else %> 
        <td class="payment-user"><%= User.find_by_id(payment.sender_id).first_name %></td>  
        <td class="owe-arrow">
          <svg width="100" height="70" xmlns="http://www.w3.org/2000/svg"><
            <g>
              <polyline points=" 50,0 78.383,34.383 50,66.766 " fill="#0f0"></polyline>
            </g>
          </svg>
        </td>
        <% end %>
        <td class="payment-amount"><%= "#{number_to_currency(payment.amount)}" %></td>
        <td class="paid-date"><%= payment.updated_at.strftime("%m/%d/%Y") %></td>
      </tr>
      <tr class="spacer"></tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/payments/index.html.erb
<% content_for :body_class, "payment-page" %>
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in" id="flash">
      <%= message %>
    </div>
  <% end %>
<div class="welcome-message">
<!-- TS - it's generally bad syntax to include ERB in HTML. Instead, consider content_tag(:span, "Hi, ...", class: 'greeting') -->
<!-- TS - both of these look like they should be divs not spans -->
  <span class="greeting"><%= "Hi, #{current_user.first_name}!" %></span>
  <br />
  <span class="owe-message">
  <% if @net_total > 0 %>
    <%= "You are owed #{number_to_currency(@net_total)}" %>
  <% elsif @net_total < 0 %>
    <%= "You owe #{number_to_currency(@net_total.abs)} total." %>
  <% else %>
    <%= "You are all square!" %>
  <% end %>
  </span>
</div>

<div class="new-payment-link"><%= link_to 'Add Payment', new_payment_path, :class=>"btn btn-default" %>
<%= link_to 'Payment History', history_path , :class=>"btn btn-default" %></div>

<% if @recipient_payments.present? %>
<table class="payment-table">
<h1 class="table-title owed-table" >Money You Are Owed</h1>
  <tbody>
    <% @recipient_payments.each do |payment| %>
      <tr class="payment-<%= payment.id %>">
        <td class="payment-user"><%= User.find_by_id(payment.sender_id).first_name %></td>
        <%= render 'green_arrow' %>
        <!-- TS - unnecessary interpolation -->
        <td class="payment-amount"><%= "#{number_to_currency(payment.amount)}" %></td>
      </tr>
      <!-- TS - as discussed, I think this method is going to be  -->
      <tr class="links payment-<%= payment.id %>">
        <td></td>
        <!-- TS - instead of using detail-link and/or override-link, style the a tag directly or apply these classes directly to the link -->
        <td class="detail-link override-link"><%= link_to 'Details', edit_payment_path(payment), "data-toggle" => "tooltip", "data-placement" => "bottom", "data-original-title" => "#{payment.note}", "trigger"=>"hover focus"%></td>
        <td class="paid-link">
          <div id="paid-msg"></div>
          <%= link_to 'Paid', '#', class: 'js-update-paid', data: { payment: payment.id } %></td>
      </tr>
      <tr class="payment-<%= payment.id %> spacer"></tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% if @sender_payments.present? %>
<table class="payment-table">
<h1 class="table-title owe-table" >Money You Owe</h1>
  <tbody class="payment-table">
    <% @sender_payments.each do |payment| %>
      <tr class="payment-<%= payment.id %>">
        <!-- TS - avoid SQL calls in your view. Instead, an association should be made within the payment model to retrieve this. Will go over in the next review. -->
        <td class="payment-user"><%= User.find_by_id(payment.recipient_id).first_name %></td>
        <%= render 'red_arrow' %>
        <!-- TS - unnecessary interpolation -->
        <td class="payment-amount"><%= "#{number_to_currency(payment.amount)}" %></td>
      </tr>
      <tr class="links payment-<%= payment.id %>">
        <td></td>
        <!-- TS - hash rocket -->
        <td class="detail-link"><%= link_to 'Details', edit_payment_path(payment), "data-toggle" => "tooltip", "data-placement" => "bottom", "title" => "#{payment.note}" %></td>
        <td class="paid-link">
          <div id="paid-msg"></div>
          <%= link_to 'Paid', '#', class: 'js-update-paid', data: { payment: payment.id } %></td>
      </tr>
      <tr class="payment-<%= payment.id %> spacer"></tr>
    <% end %>
  </tbody>
</table>
<div class="bottom-space"></div>
<!-- TS - don't put javascript in a view unless you're feeding dynamic data and it's very, very, very minimal. All JS should be in a file -->
<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#flash').remove();
  }, 5000);
 })
</script>
<% end %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form' %>

<div class="cancel-link">
<%= link_to 'Cancel', payments_path %>
</div>
<% flash.each do |type, messages| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in error-message">
      <ul class="errors">
        <% messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/payments/show.html.erb
<!-- TS - delete view if unnecessary -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @payment.sender_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @payment.recipient_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Note:</strong>
  <%= @payment.note %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>