config/routes.rb
Rails.application.routes.draw do
  resources :payment_users
  resources :payments, except: [:show, :destroy]
  resources :users, except: [:show, :destroy]

  root 'users#login'

  get 'login' => 'users#login', as: :login

  get 'signup' => 'users#new', as: :signup

  get '/history' => 'payments#history', as: :history

  post '/login' => 'users#authenticate'

  post '/paid' => 'payments#paid', as: 'paid'

  delete 'logout/:id' => "users#logout", as: :logout

end

app/models/payment_user.rb
# TS - You can probably get rid of this model
class PaymentUser < ActiveRecord::Base
	belongs_to :payment
	belongs_to :user

end

app/controllers/payment_users_controller.rb
# TS - remove this file, as well as its views folder, as you don't appear to be using it
class PaymentUsersController < ApplicationController
  before_action :set_payment_user, only: [:show, :edit, :update, :destroy]

  # GET /payment_users
  # GET /payment_users.json
  def index
    @payment_users = PaymentUser.all
  end

  # GET /payment_users/1
  # GET /payment_users/1.json
  def show
  end

  # GET /payment_users/new
  def new
    @payment_user = PaymentUser.new
  end

  # GET /payment_users/1/edit
  def edit
  end

  # POST /payment_users
  # POST /payment_users.json
  def create
    @payment_user = PaymentUser.new(payment_user_params)

    respond_to do |format|
      if @payment_user.save
        format.html { redirect_to @payment_user, notice: 'Payment user was successfully created.' }
        format.json { render :show, status: :created, location: @payment_user }
      else
        format.html { render :new }
        format.json { render json: @payment_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_users/1
  # PATCH/PUT /payment_users/1.json
  def update
    respond_to do |format|
      if @payment_user.update(payment_user_params)
        format.html { redirect_to @payment_user, notice: 'Payment user was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_user }
      else
        format.html { render :edit }
        format.json { render json: @payment_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_users/1
  # DELETE /payment_users/1.json
  def destroy
    @payment_user.destroy
    respond_to do |format|
      format.html { redirect_to payment_users_url, notice: 'Payment user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_user
      @payment_user = PaymentUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_user_params
      params[:payment_user]
    end
end

app/helpers/payment_users_helper.rb
module PaymentUsersHelper
end

app/views/payment_users/_form.html.erb
<%= form_for(@payment_user) do |f| %>
  <% if @payment_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_user.errors.count, "error") %> prohibited this payment_user from being saved:</h2>

      <ul>
      <% @payment_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_users/edit.html.erb
<h1>Editing Payment User</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_user %> |
<%= link_to 'Back', payment_users_path %>

app/views/payment_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payment Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_users.each do |payment_user| %>
      <tr>
        <td><%= link_to 'Show', payment_user %></td>
        <td><%= link_to 'Edit', edit_payment_user_path(payment_user) %></td>
        <td><%= link_to 'Destroy', payment_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment user', new_payment_user_path %>

app/views/payment_users/new.html.erb
<h1>New Payment User</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_users_path %>

app/views/payment_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payment_user_path(@payment_user) %> |
<%= link_to 'Back', payment_users_path %>